// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module("gemStore", ["store-directives"]);

  app.controller("StoreController", [
    "$http", function($http) {
      var store;
      store = this;
      store.products = [];
      return $http.get("/store-products.json").success(function(data) {
        return store.products = data;
      });
    }
  ]);

  app.controller("ReviewController", function() {
    this.review = {};
    return this.addReview = function(product) {
      product.reviews.push(this.review);
      this.review = {};
    };
  });

}).call(this);
