// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module("store-directives", []);

  app.directive("productDescription", function() {
    return {
      restrict: "E",
      templateUrl: "product-description.html"
    };
  });

  app.directive("productReviews", function() {
    return {
      restrict: "E",
      templateUrl: "product-reviews.html"
    };
  });

  app.directive("productSpecs", function() {
    return {
      restrict: "A",
      templateUrl: "product-specs.html"
    };
  });

  app.directive("productTabs", function() {
    return {
      restrict: "E",
      templateUrl: "product-tabs.html",
      controller: function() {
        this.tab = 1;
        this.isSet = function(checkTab) {
          return this.tab === checkTab;
        };
        return this.setTab = function(activeTab) {
          return this.tab = activeTab;
        };
      },
      controllerAs: "tab"
    };
  });

  app.directive("productGallery", function() {
    return {
      restrict: "E",
      templateUrl: "product-gallery.html",
      controller: function() {
        this.current = 0;
        return this.setCurrent = function(imageNumber) {
          return this.current = imageNumber || 0;
        };
      },
      controllerAs: "gallery"
    };
  });

}).call(this);
